In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
training_set = tf.keras.utils.image_dataset_from_directory(
    '/kaggle/input/potato-plant-dataset/potato_dataset/train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

Found 1722 files belonging to 3 classes.


In [3]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    '/kaggle/input/potato-plant-dataset/potato_dataset/valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

Found 215 files belonging to 3 classes.


In [4]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 3), dtype=tf.float32, name=None))>

In [5]:
for x, y in training_set:
    print(x, x.shape)
    print(y, y.shape)
    break

# x is training example and y is label

tf.Tensor(
[[[[ 14.5   14.5   16.5 ]
   [ 14.    14.    16.  ]
   [ 13.    13.    15.  ]
   ...
   [149.   146.   153.  ]
   [148.5  145.5  152.5 ]
   [143.   140.   147.  ]]

  [[ 14.5   14.5   16.5 ]
   [ 14.    14.    16.  ]
   [ 13.    13.    15.  ]
   ...
   [158.75 155.75 162.75]
   [152.75 149.75 156.75]
   [152.   149.   156.  ]]

  [[ 14.5   14.5   16.5 ]
   [ 14.    14.    16.  ]
   [ 13.    13.    15.  ]
   ...
   [173.75 170.75 177.75]
   [152.75 149.75 156.75]
   [154.5  151.5  158.5 ]]

  ...

  [[179.25 176.25 185.25]
   [185.5  182.5  191.5 ]
   [185.5  182.5  191.5 ]
   ...
   [185.75 182.75 189.75]
   [183.75 180.75 187.75]
   [185.25 182.25 189.25]]

  [[179.25 176.25 185.25]
   [185.5  182.5  191.5 ]
   [185.5  182.5  191.5 ]
   ...
   [182.5  179.5  186.5 ]
   [181.75 178.75 185.75]
   [190.   187.   194.  ]]

  [[181.5  178.5  187.5 ]
   [184.25 181.25 190.25]
   [184.25 181.25 190.25]
   ...
   [189.75 186.75 193.75]
   [184.25 181.25 188.25]
   [181.75 178.75 18

In [6]:
from tensorflow.keras.layers import Dense, Conv2D, MaxPool2D, Flatten, Dropout
from tensorflow.keras.models import Sequential

In [7]:
# model loading
model = Sequential()

In [8]:
#Building Convolution Layer

model.add(Conv2D(filters=32, kernel_size=3, padding='same', activation='relu', input_shape=[128,128,3]))
model.add(Conv2D(filters=32, kernel_size=3, activation='relu')) #input shape needs to be paased only in the first layer
model.add(MaxPool2D(pool_size=2, strides =2))

/opt/conda/lib/python3.10/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [9]:
model.add(Conv2D(filters=64, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=64, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2, strides =2))

In [10]:
model.add(Conv2D(filters=128, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=128, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2, strides =2))

In [11]:
model.add(Conv2D(filters=256, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=256, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2, strides =2))

In [12]:
model.add(Conv2D(filters=512, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=512, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2, strides =2))

In [13]:
model.add(Dropout(0.25)) #to avoid overfitting

In [14]:
#flatten layer

model.add(Flatten())

In [15]:
#dense layer

model.add(Dense(units=1500, activation='relu'))

In [16]:
model.add(Dropout(0.25))


In [17]:
#Output Layer
#no of output classes = 3
model.add(Dense(units=3, activation='softmax'))

In [18]:
model.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.0001), loss='categorical_crossentropy', metrics = ['accuracy'])

In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 126, 126, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 63, 63, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 63, 63, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 61, 61, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 30, 30, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 28, 28, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 14, 14, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 14, 14, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 12, 12, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 6, 6, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_8 (Conv2D)               │ (None, 6, 6, 512)      │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_9 (Conv2D)               │ (None, 4, 4, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1500)           │     3,073,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 1500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │         4,503 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,790,227 (29.72 MB)

 Trainable params: 7,790,227 (29.72 MB)

 Non-trainable params: 0 (0.00 B)

In [20]:
training_history = model.fit(x=training_set, validation_data=validation_set, epochs=15)

Epoch 1/15


I0000 00:00:1731856842.982523    1051 service.cc:145] XLA service 0x793108002450 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1731856842.982576    1051 service.cc:153]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0


 7/54 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.4315 - loss: 2.5674

I0000 00:00:1731856850.578442    1051 asm_compiler.cc:369] ptxas warning : Registers are spilled to local memory in function 'loop_add_subtract_fusion_5', 4 bytes spill stores, 12 bytes spill loads
ptxas warning : Registers are spilled to local memory in function 'loop_add_subtract_fusion_4', 4 bytes spill stores, 12 bytes spill loads
ptxas warning : Registers are spilled to local memory in function 'loop_add_subtract_fusion_3', 4 bytes spill stores, 12 bytes spill loads

I0000 00:00:1731856850.587015    1051 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - accuracy: 0.4771 - loss: 1.3983

I0000 00:00:1731856858.841425    1053 asm_compiler.cc:369] ptxas warning : Registers are spilled to local memory in function 'loop_add_subtract_fusion_5', 4 bytes spill stores, 12 bytes spill loads
ptxas warning : Registers are spilled to local memory in function 'loop_add_subtract_fusion_4', 4 bytes spill stores, 12 bytes spill loads
ptxas warning : Registers are spilled to local memory in function 'loop_add_subtract_fusion_3', 4 bytes spill stores, 12 bytes spill loads



54/54 ━━━━━━━━━━━━━━━━━━━━ 21s 195ms/step - accuracy: 0.4778 - loss: 1.3914 - val_accuracy: 0.7628 - val_loss: 0.7196
Epoch 2/15
54/54 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - accuracy: 0.6799 - loss: 0.7208 - val_accuracy: 0.8465 - val_loss: 0.3741
Epoch 3/15
54/54 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - accuracy: 0.8241 - loss: 0.4211 - val_accuracy: 0.9209 - val_loss: 0.2781
Epoch 4/15
54/54 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - accuracy: 0.9034 - loss: 0.2677 - val_accuracy: 0.9163 - val_loss: 0.1821
Epoch 5/15
54/54 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - accuracy: 0.9285 - loss: 0.1790 - val_accuracy: 0.9349 - val_loss: 0.1816
Epoch 6/15
54/54 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - accuracy: 0.9367 - loss: 0.1536 - val_accuracy: 0.9628 - val_loss: 0.1159
Epoch 7/15
54/54 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - accuracy: 0.9512 - loss: 0.1351 - val_accuracy: 0.9488 - val_loss: 0.1270
Epoch 8/15
54/54 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - accuracy: 0.9809 - loss: 0.0616 - val_accuracy: 0.9581 - val_loss: 

In [21]:
#Model Evaluation on validation set

valid_loss, valid_acc= model.evaluate(validation_set)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9508 - loss: 0.1578


In [22]:
print(valid_loss, valid_acc)

0.17078576982021332 0.9488372206687927


In [23]:
#saving_model
model.save('my_model.keras')

In [ ]:
# Assuming `model` is your trained Keras model
converter = tf.lite.TFLiteConverter.from_keras_model(model)

# Convert the model to TensorFlow Lite format
tflite_model = converter.convert()

In [ ]:
#recording model history in JSON format

import json
with open("training_history_v3.json","w") as f:
    json.dump(training_history.history,f)

In [1]:
epochs = range(1, len(training_history.history['accuracy']) + 1)
plt.plot(epochs, training_history.history['accuracy'], label='Training Accuracy')
plt.plot(epochs, training_history.history['val_accuracy'], color='red', label='Validation Accuracy')
plt.xlabel("Number of Epochs")
plt.ylabel("Accuracy")
plt.title("Visualization of Accuracy Results")
plt.legend()
plt.show()


NameError: name 'training_history' is not defined

In [ ]:
class_name = validation_set.class_names

In [ ]:
class_name

In [ ]:
test_set = tf.keras.utils.image_dataset_from_directory(
    '/kaggle/input/potato-plant-dataset/potato_dataset/valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=False, #will pass sequentially
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

In [ ]:
y_pred = model.predict(test_set)
y_pred, y_pred.shape


In [ ]:
# take the class having maximum value
predicted_categories = tf.argmax(y_pred, axis =1)
predicted_categories

In [ ]:
true_categories = tf.concat([y for x,y in test_set], axis = 0)
true_categories

In [ ]:
Y_true = tf.argmax(true_categories, axis =1)
Y_true

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(Y_true, predicted_categories, target_names=class_name))

In [ ]:
 #calculate consuion matrix
from sklearn.metrics import confusion_matrix

In [ ]:
cm = confusion_matrix(Y_true, predicted_categories)

In [ ]:
print(cm)
print(cm.shape)

In [ ]:
# visualization
plt.figure(figsize=(10,10))
sns.heatmap(cm, annot=True,annot_kws={'size':10})
plt.xlabel("Predicted class", fontsize=20)
plt.ylabel("Actual class", fontsize=20)
plt.title("Plant Disease Prediction Confusion Matrix", fontsize = 30)
plt.show

In [ ]:
import shutil
import os

# Define the source folder and the destination zip file path
source_folder = '/kaggle/working/my_model'
zip_file = '/kaggle/working/my_model.zip'

# Create a zip archive of the source folder
shutil.make_archive(zip_file.replace('.zip', ''), 'zip', source_folder)

print(f'Folder "{source_folder}" has been successfully zipped as "{zip_file}".')
